version: 1
formatters:
  simple:
    format: "{asctime} | {levelname}: {message:<50} ({filename}:{lineno})"
    style: "{"
  colored: # custom colored formatter (see log.py for more info)
    format: "{asctime} | {levelname} {message:<50} ({filename}:{lineno})"
    style: "{"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
  logfile:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logfiles/run.log
    mode: w+
  logfileColor:
    class: logging.FileHandler
    level: DEBUG
    formatter: colored
    filename: logfiles/runColor.log
    mode: w+
loggers:
  mainLogger:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]